name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment_pipeline:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm run dependencies:install
      - name: Run Linting
        run: npm run eslint
      - name: Run Tests
        run: npm run test
      - name: Build the application
        run: npm run build
      - name: Run end-to-end Tests
        uses: cypress-io/github-action@6c143abc292aa835d827652c2ea025d098311070
        with:
          command: npm run test:e2e
          start: npm run start
          wait-on: 'http://localhost/3001'
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl "$deploy_url"
      - name: Discord Success Notification
        if: success()
        uses: rjstone/discord-webhook-notify@c2597273488aeda841dd1e891321952b51f7996f
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: info
          username: Github
          title: A new version of Phonebook app deployed
          description: to ${{ vars.RENDER_URL }} by ${{ github.actor }}
      - name: Discord Failure Notification
        if: failure()
        uses: rjstone/discord-webhook-notify@c2597273488aeda841dd1e891321952b51f7996f
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: error
          username: Github
          title: Build Failed
          description: commit [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}) by ${{ github.actor }} broke the build
  
  tag_release:
    needs: [deployment_pipeline]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: 'patch'